### ISSUE TITLE
TBC:C 2.5.2 LUA Error

### ISSUE THREAD

**Issue by crespire** [hurricup/WoW-Ace3#2]
Getting this error every time I log in.

`Message: ...ace\AddOns\Attune\Libs\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "PARTY_MEMBERS_CHANGED"
Time: Fri Sep  3 09:21:16 2021
Count: 1
Stack: ...ace\AddOns\Attune\Libs\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "PARTY_MEMBERS_CHANGED"
[string "=[C]"]: in function `RegisterEvent'
[string "@Interface\AddOns\Attune\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:33: in function `OnUsed'
[string "@Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:142: in function `RegisterEvent'
[string "@Interface\AddOns\Prat-3.0\modules\PlayerNames.lua"]:1132: in function `OnModuleEnable'
[string "@Interface\AddOns\Prat-3.0\addon\modules.lua"]:189: in function <Interface\AddOns\Prat-3.0\addon\modules.lua:178>
[string "=[C]"]: ?
[string "@Interface\AddOns\Attune\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ace\AddOns\Attune\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Attune\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Attune\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface\AddOns\Attune\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ace\AddOns\Attune\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: `<none>``

**Comment by hurricup** [comment]
This is not an active repo.
